#programs used
$terminal = alacritty
$fileManager = nemo
$menu = rofi -disable-history -show drun
$browser = firefox

#autostart applications
#system starts
exec-once=waybar &
exec-once=dunst &
exec-once=hyprpaper
exec-once=sleep 2 && /home/bailey/shellscripts/wallp.sh > /home/bailey/shellscripts/wallp.out
exec-once = swayidle -w timeout 3600 "hyprctl dispatch dpms off" resume "hyprctl dispatch dpms on"
exec-once = /usr/lib/polkit-kde-authentication-agent-1

#personal autostarts
exec-once=sleep 10 && steam -silent %U
exec-once=sleep 10 && vesktop --start-minimized

