source = ~/.config/hypr/themes/fuji.conf
source = ~/.config/hypr/core/monitors.conf
source = ~/.config/hypr/core/programs.conf
source = ~/.config/hypr/core/mousecur.conf
source = ~/.config/hypr/core/appearance.conf
source = ~/.config/hypr/core/animation.conf
source = ~/.config/hypr/core/input.conf
source = ~/.config/hypr/core/winwork.conf


