#workspace layout
workspace = 1,monitor:DP-3
workspace = 2,monitor:DP-3
workspace = 3,monitor:DP-3
workspace = 4,monitor:DP-4
workspace = 5,monitor:DP-4
workspace = 6,monitor:DP-4, on-created-empty: spotify-launcher
workspace = 7,monitor:DP-3
workspace = 9,monitor:DP-3
workspace = 11,monitor:DP-3, on-created-empty:[float] qalculate-gtk

#window rules
windowrule {
 name = spotify
 match:class = spotify
 opacity = 0.8
}

windowrule {
 name = firefox
 match:class = firefox
 opacity = 1.0
}

windowrule {
    name = godotdebug
    match:title = ^(.*DEBUG.*)$
    workspace = 9
}
